id: A288DCA8C
title: Brief Sang Offering to Purify Contamination
type: translation
pechas:
- I6C7C84BF
- I4618FBA0
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:11:56.772880
  last_modified_at: 2023-01-04 13:11:56.772884
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I6C7C84BF/44DC: 71D2
  I4618FBA0/C4C6: 71D2
